# Generated by Django 4.1.7 on 2023-04-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_indexses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefilmwork',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='movies.person'),
        ),
    ]
