# Generated by Django 4.1.7 on 2023-04-02 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_add_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefilmwork',
            name='film_work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_genres', to='movies.filmwork'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='film_work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_persons', to='movies.filmwork'),
        ),
    ]
